package awsmt

import (
	"context"
	"fmt"
	"github.com/aws/aws-sdk-go/aws"
	"github.com/aws/aws-sdk-go/aws/session"
	"github.com/aws/aws-sdk-go/service/mediatailor"
	"github.com/hashicorp/terraform-plugin-sdk/v2/diag"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	"os"
)

func Provider() *schema.Provider {
	return &schema.Provider{
		Schema: map[string]*schema.Schema{
			"profile": {
				Type:        schema.TypeString,
				Optional:    true,
				Default:     "",
				Description: "The profile generated by the SSO login. You can find the profile(s) name in '~/.aws/config'. SSO login will not be used if the profile name is not specified and no environmental variable called 'aws_profile' is found.",
			},
			"region": {
				Type:        schema.TypeString,
				Optional:    true,
				Description: "AWS region. defaults to 'eu-central-1'.",
			},
		},
		ResourcesMap: map[string]*schema.Resource{
			"awsmt_playback_configuration": resourcePlaybackConfiguration(),
			"awsmt_channel":                resourceChannel(),
			"awsmt_source_location":        resourceSourceLocation(),
			"awsmt_vod_source":             resourceVodSource(),
			"awsmt_live_source":            resourceLiveSource(),
			"awsmt_channel_policy":         resourceChannelPolicy(),
		},
		DataSourcesMap: map[string]*schema.Resource{
			"awsmt_playback_configuration": dataSourcePlaybackConfiguration(),
			"awsmt_channel":                dataSourceChannel(),
			"awsmt_source_location":        dataSourceSourceLocation(),
			"awsmt_vod_source":             dataSourceVodSource(),
			"awsmt_live_source":            dataSourceLiveSource(),
			"awsmt_channel_policy":         dataSourceChannelPolicy(),
		},
		ConfigureContextFunc: providerConfigure,
	}
}

func providerConfigure(_ context.Context, d *schema.ResourceData) (interface{}, diag.Diagnostics) {
	var diags diag.Diagnostics
	region, ok := d.GetOk("region")
	if !ok {
		region = "eu-central-1"
	}

	var sess *session.Session
	var err error
	var profile = ""

	if val := d.Get("profile"); val.(string) != "" {
		profile = val.(string)
	} else if env := os.Getenv("AWS_PROFILE"); env != "" {
		profile = os.Getenv("AWS_PROFILE")
	}

	if profile != "" {
		sess, err = session.NewSessionWithOptions(session.Options{
			SharedConfigState: session.SharedConfigEnable,
			Config: aws.Config{
				Region: aws.String(region.(string)),
			},
			Profile: profile,
		})
	} else {
		sess, err = session.NewSession(&aws.Config{Region: aws.String(region.(string))})
	}

	if err != nil {
		diags = append(diags, diag.Diagnostic{
			Severity: diag.Error,
			Summary:  fmt.Sprintf("Unable to initialize session in region '%s'", region),
			Detail:   fmt.Sprintf("Unable to create a new session for the specified region: %s", err),
		})
		return nil, diags
	}
	c := mediatailor.New(sess)
	return c, diags
}
