name: CI

on:
  push:
    branches:
      - "**"

permissions:
  id-token: write
  contents: write

jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
      - uses: actions/setup-python@v6
      - uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
      - uses: golangci/golangci-lint-action@v9
        with:
          version: latest
      - run: >-
          set -eou pipefail &&
          make setup &&
          make lint
        working-directory: tests/docs
      - run: npx prettier . --check

  test:
    name: Test
    needs: [lint, snyk]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: ${{ secrets.ROLE_TO_ASSUME }}
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ secrets.AWS_REGION }}
      - run: make test

  snyk:
    name: Snyk Scan
    runs-on: ubuntu-latest
    env:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
      - uses: snyk/actions/setup@master
      - run: >-
          set -eou pipefail &&
          make setup
        working-directory: tests/docs
      - run: >-
          set -eou pipefail && 
          . tests/docs/venv/bin/activate && 
          snyk test
          --severity-threshold=medium
          --all-projects
          --fail-on=upgradable
      - run: >-
          set -eou pipefail && 
          . tests/docs/venv/bin/activate && 
          snyk code test
          --severity-threshold=medium
          --all-projects

  release:
    name: Release
    needs: [test, snyk]
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v6
        with:
          node-version: 24
      - run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_SEMANTIC_RELEASE }}
